version: '3.6'

services:
  robo:
    build: .
    container_name: robo_com_logs
    volumes:
      - ./app_logs:/app_logs

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.18
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./app_logs:/app_logs
    command: bash -c "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat -e -c /usr/share/filebeat/filebeat.yml"
    depends_on:
      - robo