filebeat.inputs:
- type: log
  id: robo1
  enabled: true
  paths:
    - /app/*.json
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "10.0.0.113:5601"

output.elasticsearch:
  hosts: ["10.0.0.113:9200"]
  preset: balanced
  protocol: "https"
  username: "elastic"
  password: "6sLjmJle2ISmPhAdw8qZ"
  ssl.verification_mode: none

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~